### ISSUE TITLE
Incorrect licence type sometimes shown in metadata box on the dataset page

### ISSUE THREAD

**Issue by deborahchua** [alphagov/datagovuk_find#1327]
We have found some datasets where the licence type shown should be mapped one of the default options in CKAN, and if not, shows `Other` or `None`.

 The default list is defined here - https://github.com/ckan/ckan/blob/12c5e9adb77ace52b7d539c91f910b3c9ad510d6/ckan/model/license.py#L75-L90

It looks like the licence type is pulled in as additional data, and can happen to both harvested and non-harvested data.

For example:
![Screenshot 2024-10-21 at 11 31 31](https://github.com/user-attachments/assets/a0446fe7-11b0-42a3-9b9e-6a675e686311)

- [Page in CKAN](https://ckan.publishing.service.gov.uk/dataset/edit/current-and-last-100-days-of-planning-applications)
- [Page in CKAN showing additional information](https://ckan.publishing.service.gov.uk/dataset/current-and-last-100-days-of-planning-applications/resource/b8b57dfc-5933-4d3e-9c76-f038e90d4bf3?inner_span=True)
- [OS page](https://www.data.gov.uk/dataset/8fec4f1a-40f8-4454-9822-31833d8b6989/current-and-last-100-days-of-planning-applications)
- [Solr page](https://www.integration.data.gov.uk/dataset/solr/8fec4f1a-40f8-4454-9822-31833d8b6989/current-and-last-100-days-of-planning-applications)

Other examples:

- [https://www.integration.data.gov.uk/dataset/solr/dc37c693-d910-457a-bbee-70a4037715bb/business-rates1](https://www.integration.data.gov.uk/dataset/solr//dc37c693-d910-457a-bbee-70a4037715bb/business-rates1)
- https://www.integration.data.gov.uk/dataset/solr/e2000a04-38a4-4574-8cf8-0f61155e21ed/kpi-opc09c
- https://www.integration.data.gov.uk/dataset/solr/fbdb0032-3f91-42b9-a270-9b0bf2c66f8e/mushroom_survey_england

![Screenshot 2024-10-21 at 11 30 33](https://github.com/user-attachments/assets/07d2e460-7310-4dec-9fe0-5b96bef0f607)

**Comment by deborahchua** [comment]
I ran a facet query in Solr using `license_id` as a facet field and returns:

```
"facet_fields":{
      "license_id":[
        "uk-ogl",25775,
        "cc-by",975,
        "OGL-UK-3.0",402,
        "notspecified",119,
        "other-nc",49,
        "cc-zero",17,
        "other-closed",17,
        "other-pd",13,
        "unpublished",11,
        "cc-by-sa",6,
        "other-open",6,
        "odc-odbl",5,
        "odc-by",4,
        "odc-pddl",3,
        "__other__",2,
        "cc-nc",1,
        "ogl",1,
        "other-at",1]}
```
Solr query used - `/solr/ckan/select?fq=license_id%3A"__other__"&indent=true&q.op=OR&q=*%3A*&rows=100`

`uk-ogl` is the code we use to filter datasets that use the standard OGL licence (currently version 3). Datasets with `OGL-UK-3.0` should also be mapped to the same code.
Example query to find individual datasets using a specific licence ID - `/solr/ckan/select?fq=license_id%3A"OGL-UK-3.0"&indent=true&q.op=OR&q=*%3A*&rows=100`

**Comment by AgaDufrat** [comment]
https://github.com/alphagov/datagovuk_find/pull/1359
