### ISSUE TITLE
Search separately for each individual whitespace-separated term

### ISSUE THREAD

**Issue by deborahchua** [alphagov/datagovuk_find#1340]
By default, Solr treats user input as as single search term and does not require including quotes, whereas for OS it does.

This means when e.g. 
- `animal health` is entered, we should be splitting it by whitespace and Solr should be searching for `animal` or `health`, and returning all results for both terms.
- `"animal health"` is entered, we should not be splitting by whitespaces

Solr has a parameter called `sow` (split on whitespace) which is set to `false` by default.

**Comment by AgaDufrat** [comment]
Resources:
- https://sease.io/2021/05/apache-solr-sow-parameter-split-on-whitespace-and-multi-field-full-text-search.html
- https://solr.apache.org/guide/6_6/the-standard-query-parser.html
