### ISSUE TITLE
Fix search tokenisation and weighting

### ISSUE THREAD

**Issue by govuklaurence** [alphagov/datagovuk_find#154]
We still get local datasets ranked higher than national datasets even if the search wasn't narrowed down by location.

Local search terms don't rank searches from that location higher

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [We still get local datasets ranked higher than national datasets even if the search wasn't narrowed down by location](https://trello.com/c/xbV8pAtO/372-we-still-get-local-datasets-ranked-higher-than-national-datasets-even-if-the-search-wasnt-narrowed-down-by-location)
