### ISSUE TITLE
Run Find locally with a single script / task

### ISSUE THREAD

**Issue by TobyRet** [alphagov/datagovuk_find#233]
- make it easy for other developers to run the application 
- create a script or task that seeds elasticsearch with some dummy data and runs the app.
- update README with instructions
- maybe have two running options? One that seeds elasticsearch with a small subset of data (optimised for speed) the other that imports all datasets (this will take much longer)

**Comment by laurentqro** [comment]
https://github.com/datagovuk/find_data_beta/pull/279

**Comment by laurentqro** [comment]
I'll also put up a script to seed ES

**Comment by laurentqro** [comment]
Actually, that script already exists on the Publish repo, and it makes sense that it should be there. :)
