### ISSUE TITLE
Ministry of Justice organogram does not render, and the data makes no sense

### ISSUE THREAD

**Issue by MatMoore** [alphagov/datagovuk_find#685]
# Context
There is a page on data.gov.uk called [Organogram of Staff Roles & Salaries](https://data.gov.uk/dataset/a90a9f70-e28c-4a95-a7a7-f79d12fbe219/organogram-of-staff-roles-salaries) for the Ministry of Justice.

[According to the guidance, this data is supposed to be updated every 6 months](https://guidance.data.gov.uk/publish_and_manage_data/harvest_or_add_data/add_data/#publishing-organograms).

The latest data on this page is dated 2nd July 2019.

# Problem
If you click through to either dataset (junior or senior), the Organogram does not render. The page throws javascript exceptions:

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at klass.addNode (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:16543)
    at application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:20505
    at klass.construct (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:20512)
    at klass.loadJSON (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:20672)
    at Object.showSpaceTree (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:33516)
    at Object.complete (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:33038)
    at Object.CsvToJson [as parse] (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:31901)
    at Object.success (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:33032)
    at fire (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:3233)
    at Object.fireWith [as resolveWith] (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:3363)
```

```
TypeError: Cannot set property '_depth' of undefined
    at Object.computeLevels (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:17431)
    at klass.Graph.<computed> [as computeLevels] (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:17781)
    at klass.reposition (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:21370)
    at klass.refresh (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:21365)
    at Object.resize (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:15236)
    at klass.resize (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:15592)
    at klass.resize (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:15349)
    at application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:33510
    at dispatch (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:5227)
    at elemData.handle (application-fa403162f9202d471a200ecb4c76dcb309eeffc4ace8459399951998510c6c46.js:4879)
```

# Cause
The javascript in this repository makes multiple incorrect assumptions about the data.

Firstly, it requires the datasets to be named in a very particular way:

https://github.com/alphagov/datagovuk_find/blob/f7888fad32d6ee608f842044108a7f8a47074de0/app/assets/javascripts/organograms/org-data-loader.js#L3

In this dataset, the filenames do not end in senior/junior, and the first part of the filename also contains a timestamp which differs between junior and senior. This is visible in the HTML on the two pages:

```html
<section id="organogram" data-csv-url="https://s3-eu-west-1.amazonaws.com/datagovuk-production-ckan-organogram/organogram-ministry-of-justice/resources/2019-07-02T12-40-17Z-organogram-senior-csv-data.csv"></section>
```

and

```html
<section id="organogram" data-csv-url="https://s3-eu-west-1.amazonaws.com/datagovuk-production-ckan-organogram/organogram-ministry-of-justice/resources/2019-07-02T12-38-39Z-organogram-junior-csv-data.csv"></section>
```

Because the regex does not match, `seniorCSVURL` and `juniorCSVURL` are set to the same value, `csvURL`, which is wrong.

Secondly, building the organogram depends on having [at least one top level post](https://github.com/alphagov/datagovuk_find/blob/f7888fad32d6ee608f842044108a7f8a47074de0/app/assets/javascripts/organograms/org-data-loader.js#L208). [A top level post is one with a "reports to senior post" value of "XX"](https://github.com/alphagov/datagovuk_find/blob/f7888fad32d6ee608f842044108a7f8a47074de0/app/assets/javascripts/organograms/org-data-loader.js#L202). In the 2017 dataset, we had a top level post for the Permanent Secretary, Sir Richard Heaton. In the new dataset, he reports to "NA", and there are a few other posts that also report to "NA" (the code attaches no special meaning to this).

If there are no top level posts, [`buildTree` returns undefined](https://github.com/alphagov/datagovuk_find/blob/f7888fad32d6ee608f842044108a7f8a47074de0/app/assets/javascripts/organograms/org-data-loader.js#L36) which is the cause of the first stack trace.

# Data quality issues
The data is inconsistent with the dataset published in 2017 in other ways.

It contains an extra index column in addition to the fields included in the [schema](https://github.com/datagovuk/schemas/tree/master/organogram).

```
"","Parent Department","Organisation","Unit","Reporting Senior Post","Grade","Generic Job Title","Professional/ Occupational Group","Payscale Minimum (£)","Payscale Maximum (£)","Number of Posts in FTE"
"1","Ministry of Justice","AGY - CICA","DIR - CICA","CFOG30","AO","Information Technology.Admin Officer","Digital, Technology and Data","18514","24519",1
"2","Ministry of Justice","AGY - CICA","DIR - CICA","CFOG30","AO","Operation Delivery.Admin Officer","Operational Delivery","18514","24519",1
```

The permanent secretary is now labelled "JPSCG29" instead of "MOJ01".

In fact, the unique post references don't appear to match up between 2017 and 2019 at all, except for a few of them (CICA1, LAA1, LAA10, LAA11, LAA12, LAA2, LAA3, LAA4, LAA5, LAA6, LAA7, LAA8, LAA9, OPG1, OPG2) and the job titles are not consistent for these. The new job titles are less specific and often have two parts, e.g. "Other.Director".

If you look at the combination of role reference and name, nothing has stayed the same as 2017. In 2017 the "LAA" named senior roles were
```
LAA13,David Aubrey
LAA2,James McEwen
LAA1,Shaun McNally
```

and in 2019,
```
LAA12,David Aubrey QC
LAA8,Shaun Mcnally
```

For HMCTS, in 2017

```
HMCTS213,Andrew James
HMCTS145,Eliminated
HMCTS205,Faran Johnson
HMCTS208,Guy Tompkins
HMCTS212,Jonathan Wood
HMCTS204,Kevin Gallagher
HMCTS215,Kevin Sadler
HMCTS214,Kevin Sadler
HMCTS216,Marie-Claire Uhart
HMCTS210,Paul Harris
HMCTS206,Paul Harris
HMCTS209,Richard Goodman
HMCTS211,Sidonie Kingsmill
HMCTS301,Susan Acland-Hood
HMCTS165,Vacant
HMCTS156,Vacant
HMCTS149,eliminated
```

and in 2019:

```
HMCTS59,Andrew Baigent
HMCTS67,Andrew James
HMCTS42,Faran Johnson
HMCTS14,Gemma Hewison
HMCTS75,Guy Tompkins
HMCTS9,Jonathan Wood
HMCTS73,Kevin Gallagher
HMCTS70,Kevin Sadler
HMCTS3,Louise Alexander
HMCTS66,Marie-Claire Uhart
HMCTS43,Paul Harris
HMCTS13,Richard Goodman
HMCTS1,Sidonie Kingsmill
HMCTS16,Susan Acland-Hood Andrews
```

It looks like these references are being randomly generated rather than remaining the same over time (or everyone in the department is swapping jobs).

# Suggestions
1. If content relies on javascript to render, you should monitor it for javascript errors.
2. If the javascript makes assumptions about the data beyond its schema, the data publisher application should not let you publish data that violates those assumptions (e.g. the filename patterns, the number of top level posts) 
3. If the publisher is able to preview the organogram at publish time, then they should be prompted to correct problems like this before publishing.
4. All of the post references in a department changing between one submission and the next is a sign that something funny is going on. Can you flag this to the publisher?

**Comment by cbaines** [comment]
Hi Mat,

Thanks for reporting this. I've created an internal (and private) issue to track this [1], and hopefully we'll have some updates soon.

1: https://trello.com/c/7aIfTfI6/122-ministry-of-justice-organogram-issues

**Comment by kentsanggds** [comment]
Hi Mat, 
The department needs to use the provided template as per guidance - https://guidance.data.gov.uk/publish_and_manage_data/harvest_or_add_data/add_data/#what-to-include, then it should generate the correct CSV files, as the filenames appear to indicate that they have been separately and manually uploaded.

We don't have control over data quality, it is up to the departments to maintain this so advice should be given back to the department as to how they can improve it.

I am going to close this issue as it's not really an issue, more that the user needs to follow the guidance and given additional advice to improve their data.

**Comment by MatMoore** [comment]
> the user needs to follow the guidance and given additional advice to improve their data

Can you contact them about this then? I am not the user.

**Comment by kentsanggds** [comment]
I'm presuming that it came from a zendesk ticket? 2nd line should be able
to respond with the guidance if they know which zendesk ticket to respond
to.

**Comment by MatMoore** [comment]
No, I discovered this myself and am reporting it here.

**Comment by kentsanggds** [comment]
Ah I see, I'll raise the matter with the PO but as there's other things
which are taking priority and this is just a matter of guidance this will
probably be parked for the moment.
